name: Vcpkg (Windows)

on:
  push:
    branches: [ "trunk" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    
    name: "Vcpkg on ${{ matrix.os }}"
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Vcpkg Install
      run: $env:VCPKG_INSTALLATION_ROOT\vcpkg.exe install apr-2 --head --overlay-ports ${{ github.workspace }}\build\vcpkg
